#spring.datasource.url=jdbc:postgresql://46.250.171.73:5432/postgres
spring.datasource.url=jdbc:postgresql://10.60.8.31:5432/postgres
spring.datasource.username=root
spring.datasource.password=Oz#5q9W5f#4ZUn@9
spring.jpa.properties.hibernate.default_schema=public
