spring.application.name=app
server.port=${PORT:8084}
spring.datasource.url=jdbc:postgresql://101.44.24.163:5432/kyc
spring.datasource.username=root
spring.datasource.password=Hjuuw34@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.forward-headers-strategy=native

jwt.access.secret=${JWT_ACCESS_SECRET:ijjmiGVcsQB5zlPGEKFlDaS5vB+Q25SvpLr0pdO94AFY7yhlX7wakpTzou6cHuzAhPppiN8uV8l1BrQ4SrWmOg==}
jwt.access.expiration-ms=${JWT_ACCESS_EXPIRY_MS:900000}
jwt.refresh.secret=${JWT_REFRESH_SECRET:ijjmiGVcsQB5zlPGEKFlDaS5vB+Q25SvpLr0pdO94AFY7yhlX7wakpTzou6cHuzAhPppiN8uV8l1BrQ4SrWmOg==}
jwt.refresh.expiration-ms=${JWT_REFRESH_EXPIRY_MS:1200000}

didit.api.key=Ruj1vWPpuDXcpP_oxPY40LZ-ylXMzzOtM-AshgcEJA0
