#spring.datasource.url=jdbc:postgresql://46.250.171.73:5432/whatsapp
spring.datasource.url=jdbc:postgresql://10.60.8.31:5432/whatsapp
spring.datasource.username=root
spring.datasource.password=Oxi7z5qm9W5f4ZNUnra9
